# Generated by Django 4.1 on 2025-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_options_emp_created_at_emp_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('company_contact', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('department_choices', models.TextField(default='Computer Science,Mechanical Engineering,Electrical Engineering,Civil Engineering', help_text='Enter department names separated by commas')),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('items_per_page', models.IntegerField(default=20)),
                ('enable_audit_trail', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#39B5E0', max_length=7)),
                ('secondary_color', models.CharField(default='#2596be', max_length=7)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
