# Generated by Django 4.1 on 2025-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='border_radius',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='header_style',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('transparent', 'Transparent')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='text_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
    ]
