# Generated by Django 4.1 on 2025-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_settings_border_radius_settings_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='border_radius',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='settings',
            name='header_style',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('transparent', 'Transparent')], default='gradient', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='primary_color',
            field=models.CharField(default='#50024d', max_length=7),
        ),
        migrations.AlterField(
            model_name='settings',
            name='secondary_color',
            field=models.CharField(default='#0e6001', max_length=7),
        ),
        migrations.AlterField(
            model_name='settings',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
