# Generated by Django 4.1 on 2025-05-14 13:01

from django.db import migrations, models
import emp.models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_settings_border_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to=emp.models.employee_image_path),
        ),
    ]
