# Generated by Django 4.1 on 2025-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_emp_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
