# Generated by Django 4.1 on 2025-05-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_emp_age_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
